"""initial schema

Revision ID: 8640fb57599a
Revises: 
Create Date: 2026-08-11 06:23:04.141954
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.core.database


# revision identifiers, used by Alembic.
revision: str = '8640fb57599a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('detail', app.core.database.PortableJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connector_config',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=True),
    sa.Column('client_secret_enc', sa.Text(), nullable=True),
    sa.Column('s_user', sa.String(length=50), nullable=True),
    sa.Column('s_password_enc', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=50), nullable=True),
    sa.Column('last_sync_message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('systems',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('sid', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_type', sa.String(length=20), nullable=True),
    sa.Column('landscape', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_report_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('systems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_systems_sid'), ['sid'], unique=True)

    op.create_table('users',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('admin', 'operator', 'viewer', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('reports',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('system_id', app.core.database.GUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('upload_method', sa.Enum('manual', 'auto_fetch', name='uploadmethod'), nullable=False),
    sa.Column('overall_rating', sa.Enum('red', 'yellow', 'green', 'gray', name='severity'), nullable=True),
    sa.Column('parsed_data', app.core.database.PortableJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_id', 'report_date', name='uq_report_system_date')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_report_date'), ['report_date'], unique=False)

    op.create_table('alerts',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('report_id', app.core.database.GUID(), nullable=False),
    sa.Column('system_id', app.core.database.GUID(), nullable=False),
    sa.Column('chapter', sa.String(length=150), nullable=True),
    sa.Column('severity', sa.Enum('red', 'yellow', 'green', 'gray', name='severity'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('sap_note_refs', app.core.database.PortableJSON(), nullable=True),
    sa.Column('tags', app.core.database.PortableJSON(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'deferred', name='alertstatus'), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_chapter'), ['chapter'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_system_id'), ['system_id'], unique=False)

    op.create_table('ratings_history',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('system_id', app.core.database.GUID(), nullable=False),
    sa.Column('report_id', app.core.database.GUID(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('chapter', sa.String(length=150), nullable=False),
    sa.Column('rating', sa.Enum('red', 'yellow', 'green', 'gray', name='severity'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ratings_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ratings_history_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_history_system_id'), ['system_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratings_history_system_id'))
        batch_op.drop_index(batch_op.f('ix_ratings_history_report_date'))

    op.drop_table('ratings_history')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_system_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_chapter'))

    op.drop_table('alerts')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_report_date'))

    op.drop_table('reports')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('systems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_systems_sid'))

    op.drop_table('systems')
    op.drop_table('connector_config')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
